name: porocci_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  flutter_riverpod: ^2.0.2

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  google_sign_in: ^5.4.2
  camera: ^0.10.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  carousel_slider: ^4.1.1

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/auth_icons/
    - assets/images/hero/
    - assets/images/logo/